# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Alfons
site_url: https://daelvn.github.io/alfons
docs_dir: docs-new

repo_url: https://github.com/daelvn/alfons
repo_name: daelvn/alfons

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/daelvn

# FIXME: https://github.com/squidfunk/mkdocs-material/issues/7599
plugins:
  - search
  - social

markdown_extensions:
  - toc:
      permalink: true
      permalink_leading: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  palette: 
    primary: custom
  icon:
    logo: material/pine-tree
    annotation: material/star-four-points-circle-outline
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - content.tabs.link
    - content.code.annotate
    # - toc.integrate
