# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Install glibc and yaml
    - name: Install libc6 and yaml
      run: |
        sudo apt install libc6 libc6-dev
        sudo apt install yaml
    
    # Lua
    - name: Install Lua/LuaJIT
      uses: leafo/gh-actions-lua@v6
      with:
        luaVersion: 5.1

    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v2
      with:
        # The version of LuaRocks to install, must be available on https://luarocks.github.io/luarocks/releases/
        luaRocksVersion: 3.3.1

    # Runs a single command using the runners shell
    - name: Install dependencies
      run: |
        luarocks install moonscript
        luarocks install filekit
        luarocks install ansikit
        luarocks install inotify
        luarocks install http
        luarocks install rockbuild
        luarocks install amalg

    # Compile MoonScript
    - name: Compile
      run: |
        moonc alfons/
        moonc bin/
        
    # Pack into single script
    - name: Pack
      run: |
        amalg.lua -o alfons.lua -s bin/alfons.lua alfons.compat alfons.env alfons.file alfons.getopt alfons.provide alfons.version

    # Runs a set of commands using the runners shell
    - name: rockbuild -m
      run: |
        rockbuild -m "$GITHUB_SHA"
